### ISSUE TITLE
Issue with matching properties' names

### ISSUE THREAD

**Issue by romandots** [brick/json-mapper#4]
If you have different props with the matching string in the beginning of their names (and at least two of them are PHPdoc-ed with @param), you get an error at src/Reflection/Reflector.php::149 which is incorrect.

Please, consider adding \W to the end of regular expression at src/Reflection/Reflector.php::149:

`$pattern = '/@param(.*)\$' . $parameter->getName() . '\W/';`

**Comment by BenMorel** [comment]
Thank you, fixed in [0.1.1](https://github.com/brick/json-mapper/releases/tag/0.1.1)!
